In [31]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

In [32]:
# replace=Trueで復元抽出
np.random.choice(np.arange(1,7), 10, replace=True)

array([6, 4, 1, 4, 5, 6, 4, 5, 6, 6])

In [33]:
# replace=Falseで非復元抽出
np.random.choice(np.arange(1,7), 6, replace=False)

array([1, 5, 3, 6, 4, 2])

In [34]:
# 確率を設定
p = np.random.rand(1, 6) 
print(p)
p = p / np.sum(p)
print(p)

p = p.squeeze(0)
np.random.choice(np.arange(1, 7), 10, p=p)

[[0.99864519 0.452933   0.73847938 0.74806669 0.61103101 0.88822915]]
[[0.22505267 0.10207207 0.16642222 0.1685828  0.13770072 0.20016953]]


array([5, 2, 6, 1, 1, 3, 5, 1, 5, 1])

In [69]:
mean = 0
std = 1
size = 10

# 正規分布 N(mean, std)
a = np.random.normal(mean, std, size)

low = 0
high = 1

# 一様分布 [low, high]
b = np.random.uniform(low, high, size)

# 標準正規分布
c = np.random.randn(size)

# 一様分布 [0, 1]
d = np.random.rand(size)

input = [a, b, c, d]