In [1]:
import numpy as np
import torch

In [2]:
x = np.arange(21).reshape(7,-1)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [3]:
x[3]

array([ 9, 10, 11])

In [4]:
x[3][2]

11

In [5]:
x[3,2]

11

In [6]:
id = np.arange(1, 7, 2)
x[id]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17]])

In [22]:
class Embedding:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None

    def forward(self, idx):
        W, = self.params
        self.idx = idx
        out = W[idx]
        return out

In [29]:
W = torch.arange(30).view(6,-1)
emb = Embedding(W)
idx = [i for i in range(1, W.shape[0], 2)]
# idx = 3
# out = emb(idx)
# out
emb.forward(idx)

tensor([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29]])

In [30]:
x = np.arange(10).reshape(2,-1)
x = 0
x

0

In [31]:
x = np.arange(10).reshape(2,-10)
x[...] = 0
x

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [45]:
W = np.arange(30).reshape(5, 6)
np.add.at(W, 2, 1)
print(W)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [13 14 15 16 17 18]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [44]:
a = np.array([1, 2, 3, 4])
np.add.at(a, [0, 1, 2, 2], 1)
a

array([2, 3, 5, 4])